// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e0336ebe-ea84-4a9c-8b5f-71e054917603",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nYXtS7nwN",
    "aws_user_pools_web_client_id": "4953fkiotime42d8sm0ovdmaqc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wbaf5r2zwrd7ngxxsjc7tbggdi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
